name: Schedule Post to Superstar Sites

on:
  schedule:
    - cron: "0 * * * *" # Every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Function
        run: |
          curl -X POST https://ai.statuscrawl.io/api/postSuperstarContent
