name: Post to Superstar Sites

on:
  schedule:
    # Creates a semi-random pattern between 30-60 minutes
    - cron: '15 */2 * * *' # Every 2 hours at :15 (2h 15m intervals)
    - cron: '45 1,3,5,7,9,11,13,15,17,19,21,23 * * *' # Odd hours at :45 (varying intervals)
    - cron: '30 0,2,4,6,8,10,12,14,16,18,20,22 * * *' # Even hours at :30 (varying intervals)
    - cron: '0 */2 * * *' # Every 2 hours on the hour
    - cron: '50 */3 * * *' # Every 3 hours at :50

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Add Random Delay
        run: |
          # Random delay between 0-10 minutes to further randomize timing
          DELAY=$((RANDOM % 600))
          echo "Waiting $DELAY seconds before execution..."
          sleep $DELAY
      - name: Trigger Vercel Function
        run: |
          curl -X POST https://ai.statuscrawl.io/api/postSuperStarContent
